// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clean_database.sql

package database

import (
	"context"
)

const cleanDatabase = `-- name: CleanDatabase :exec
TRUNCATE TABLE posts, feed_follows, feeds, users
`

func (q *Queries) CleanDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanDatabase)
	return err
}
