// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_by_name.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, name
FROM users
WHERE name = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) GetUser(ctx context.Context, name string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
